import type { DashboardData } from "../api/types";

export function dashboardFixture(overrides: Partial<DashboardData> = {}): DashboardData {
  return {
    mode: "live",
    asOf: "2026-07-11T09:00:00Z",
    lastUpdated: "2026-07-11T09:05:00Z",
    overallHealth: "healthy",
    dataState: "ready",
    windows: {
      currentStart: "2026-07-05T00:00:00+07:00",
      currentEnd: "2026-07-12T00:00:00+07:00",
      baselineStart: "2026-06-27T00:00:00Z",
      baselineEnd: "2026-07-04T00:00:00Z",
      businessTimezone: "Asia/Ho_Chi_Minh",
    },
    coverage: {
      feedbackItems: 1400,
      analyzedItems: 1200,
      relevantItems: 980,
      timeEligibleItems: 900,
      productAttributedItems: 720,
    },
    messages: [],
    products: [{
      id: "cerave-473",
      name: "CeraVe Foaming Cleanser 473ml",
      shortName: "CeraVe Foaming Cleanser",
      sku: "CV-473",
      category: "Cleanser",
      pack: "473 ml",
      metadataComplete: true,
      rating: 4.4,
      ratingCount: 1240,
      totalFeedback: 720,
      current: { feedback: 200, complaints: 6, positive: 140, neutral: 40 },
      baseline: { feedback: 180, complaints: 9, positive: 120, neutral: 40 },
      sentimentDelta: 3.2,
      sources: [{ sourceGroup: "owned", count: 150 }, { sourceGroup: "marketplace", count: 50 }],
      themes: [{ label: "Packaging", subtopic: null, count: 6 }],
      ratingDistribution: [{ rating: 5, count: 128 }, { rating: 4, count: 50 }, { rating: 3, count: 12 }, { rating: 2, count: 6 }, { rating: 1, count: 4 }],
      negativeFeedback: [{ label: "product_quality", subtopic: null, count: 6 }],
      problems: [{ label: "damaged_packaging", subtopic: null, count: 6 }],
    }],
    evidence: [{
      id: "feedback-1",
      productId: "cerave-473",
      text: "The cleanser arrived securely packed.",
      sourceGroup: "marketplace",
      sourcePlatform: "Shopee",
      timestamp: "2026-07-10T10:00:00Z",
      confidence: 0.91,
      stance: "support",
      topic: "packaging",
      subtopic: "seal",
      sentiment: "positive",
    }],
    primaryInsight: {
      id: "insight-1",
      title: "Packaging complaints declined",
      summary: "The current product cohort has fewer packaging complaints than its baseline.",
      topic: "packaging",
      label: "improving",
      status: "monitoring",
      confidenceLevel: "medium",
      confidenceScore: 0.76,
      recommendedActions: ["Continue monitoring the current cohort."],
      currentShare: 0.03,
      baselineShare: 0.05,
      percentagePointChange: -2,
      growthMultiple: 0.6,
    },
    benchmark: {
      comparable: true,
      reason: null,
      brands: [
        { brand: "guardian", feedback: 200, complaints: 6, positive: 140, neutral: 40, rating: 4.4, ratingCount: 1240, share: 0.03 },
        { brand: "hasaki", feedback: 190, complaints: 8, positive: 130, neutral: 36, rating: 4.3, ratingCount: 190, share: 8 / 190 },
        { brand: "watsons", feedback: 210, complaints: 7, positive: 150, neutral: 40, rating: 4.5, ratingCount: 210, share: 7 / 210 },
      ],
    },
    ...overrides,
  };
}
